# Site settings
title: "Colomé Tatché Lab"
description: "Research laboratory led by Dr. Maria Colomé Tatché"
baseurl: ""
url: "https://colomemaria.github.io"

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  people:
    output: true
    permalink: /people/:path/

# Navigation
header_pages:
  - index.md
  - people.md
